# [START runtime]
runtime: nodejs10
env: standard
automatic_scaling:
  max_instances: 1
  min_instances: 0
# [END runtime]

# [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]
